apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: busybox.v2.0.0
  namespace: placeholder
spec:
  description: |
    A busybox CSV.
  displayName: busybox
  install:
    spec:
      deployments:
      - name: busybox
        spec:
          replicas: 1
          selector:
            matchLabels:
                app: busybox
          template:
            metadata:
              labels:
                app: busybox
            spec:
              containers:
              - name: busybox
                image: busybox
                command:
                  - sleep
                  - "9000"
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider:
    name: Red Hat
  version: 2.0.0
  replaces: busybox.v1.0.0
