apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: nginx.v1.0.0
  namespace: placeholder
spec:
  description: |
    A nginx CSV.
  displayName: nginx
  install:
    spec:
      deployments:
      - name: nginx
        spec:
          replicas: 1
          selector:
            matchLabels:
                app: nginx
          template:
            metadata:
              labels:
                app: nginx
            spec:
              containers:
                - name: nginx
                  image: nginx:1.14.2
                  ports:
                  - containerPort: 80
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider:
    name: Red Hat
  version: 1.0.0
